spring:
  application:
    name: BLOG-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_service
    username: backend_development
    password: U&>RLkVXDK2r%jg5
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    redis:
      time-to-live: 60000
      key-prefix: jdj
    cache-name: blog
  redis:
    host: localhost
    port: 6379
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8082
  error:
    include-message: always
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
application:
  config:
    user-client-url: http://localhost:8081/api/v1/users